name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main  # altere se usar outra branch
env:
  DEBUG: true 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          debug: true
          script: |
            cd ${{ secrets.VPS_PATH }}
            echo "ðŸ”„ Pulling latest changes..."
            git pull origin main
            echo "ðŸ§± Rebuilding frontend container..."
            docker-compose down --remove-orphans
            echo "ðŸš€ Restarting frontend service..."
            docker-compose build --no-cache
            docker-compose up -d
            echo "âœ… Backend deployed successfully!"
